# Generated by Django 5.2.4 on 2025-07-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='time_from',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='time_to',
        ),
        migrations.AddField(
            model_name='feature',
            name='time_from',
            field=models.DateTimeField(blank=True, help_text='The time from which this feature is valid or visible.', null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='time_to',
            field=models.DateTimeField(blank=True, help_text='The time until which this feature is valid or visible.', null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Feature properties, including style overrides (e.g., {"style": {"color": "#ff0000"}}).'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='style_config',
            field=models.JSONField(blank=True, default=dict, help_text='Default JSON styling for all features in this layer. Can be overridden by individual feature attributes.'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['time_from', 'time_to'], name='features_time_fr_a2b52c_idx'),
        ),
    ]
