# Generated by Django 5.2.4 on 2025-07-22 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0002_remove_layer_time_from_remove_layer_time_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='attributes',
        ),
        migrations.AddField(
            model_name='feature',
            name='_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Additional properties in JSON format'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the feature'),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(blank=True, help_text='Feature name (shown in popups and labels)', max_length=255),
        ),
        migrations.AddField(
            model_name='feature',
            name='style_color',
            field=models.CharField(blank=True, help_text='Feature color in hex format (e.g., #ff0000)', max_length=20),
        ),
        migrations.AddField(
            model_name='feature',
            name='style_opacity',
            field=models.FloatField(blank=True, help_text='Opacity (0.0 to 1.0), falls back to layer opacity', null=True, validators=[django.core.validators.MinValueValidator(0.0, message='Opacity must be at least 0.0'), django.core.validators.MaxValueValidator(1.0, message='Opacity must be at most 1.0')]),
        ),
        migrations.AddField(
            model_name='feature',
            name='style_weight',
            field=models.FloatField(blank=True, help_text='Line weight or border width in pixels', null=True),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['name'], name='features_name_79c58c_idx'),
        ),
    ]
