# Generated by Django 5.2.4 on 2025-07-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0003_remove_feature_attributes_feature__attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Additional properties in JSON format', null=True),
        ),
    ]
