# Generated by Django 5.2.4 on 2025-07-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0004_make_attributes_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='_attributes',
        ),
        migrations.AddField(
            model_name='feature',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Additional properties in JSON format'),
        ),
    ]
