# Generated by Django 5.2.4 on 2025-07-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmap', '0005_remove_feature__attributes_feature_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='attributes',
        ),
        migrations.AddField(
            model_name='feature',
            name='_attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Additional properties in JSON format', null=True),
        ),
    ]
